# -*- coding: utf-8 -*-
"""E-commerce Transaction

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MvQM7muh4IF2_aGvXY-BYMcWzrE7yN1F

# **Import Library**
"""

## Importing the Python Library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""### **Data Understanding**

## LOAD DATASET ##
"""

df = pd.read_csv('OnlineRetail.csv', encoding='latin1') ## Loading the dataset, with an inclusion of encoding latin1 becuase of foreign symbols
print(df)

"""### Displaying of First few Rows ###"""

print(df.head()) ## Printing the top 5 rows

"""### Identify ###"""

##Evaluating shape of the column, including columns and rows
df.shape

## Types of data cells and empty cell count
df.info()

# Identify Numerical Features
numerical_features = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
print("Numerical Features:", numerical_features)

##Identify categorical Features
categorical_features = df.select_dtypes(include=['object']).columns.tolist()
print("Categorical Features:", categorical_features)

##Identifying unique Identifiers
for col in df.columns:
    print(f"{col}: {df[col].nunique()} unique values out of {len(df)} rows")

"""### Description of Dataset ###

The OnlineRetail dataset contains transactional data from a UK-based online retailer between 2010 and 2011. It has 541,909 rows and 8 columns, recording details like products purchased, quantity, price, customer ID, and country. The data mainly represents wholesale purchases from customers across 38 countries.

## Data Cleaning

# Missing Values
"""

## Identifying columns with missing values, and number of missing values per column
df.isnull().sum()

## Handling missing values by replacing with unkowns for objects, and 0 for integers and floats

# Identify string (object) columns
string_columns = df.select_dtypes(include="object").columns

# Identify numeric columns
numeric_columns = df.select_dtypes(include=["int64", "float64"]).columns

# Fill missing values in string columns with 'Unknown'
for col in string_columns:
    df[col].fillna("Unknown", inplace=True)

# Fill missing values in numeric columns with uknown
for col in numeric_columns:
    df[col].fillna("Unknown", inplace=True)

# Display dataframe
display(df)

###re evaluating empty columns
df.isnull().sum()

##Re-evluating the rows and columns to ensure compactness
df.shape

"""Missing values in the dataset were handled differently based on the data type of each column.
For categorical (object) columns such as Description and CustomerID, missing values were replaced with "Unknown" because these columns contain text labels where a placeholder makes it clear the information was not available, without distorting any analysis.
For numerical columns such as Quantity and UnitPrice, missing values were replaced with 0 because it is a neutral value that does not inflate or skew calculations like averages or totals, and it preserves all rows for further analysis.
This approach was chosen because it is simple and non-destructive, meaning no rows are deleted, which keeps the dataset complete and ensures no data is lost during analysis. It also makes the data easier to work with in subsequent steps.

## Duplicate Records
"""

###checking for duplicates
checking_duplicates = df.duplicated() #Returns True or False
sum_of_duplicates = checking_duplicates.sum() #Returns total number of duplicates found in dataset

print("The total sum of duplicates is:", sum_of_duplicates)
print(checking_duplicates)

df = df.drop_duplicates()
df.shape

print("Number of duplicate rows after cleaning:", df.duplicated().sum())

print(df)

"""## Standardization"""

df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'], errors='coerce')

# Data types
df['CustomerID'] = df['CustomerID'].astype(str)

df.info()

## Description Conversion
df['Description'] = df['Description'].str.title()

print(df)

"""# Data Validation"""

## Invalid Values
print(df[df['Quantity'] < 0].shape[0], "negative quantity rows")
print(df[df['UnitPrice'] <= 0].shape[0], "zero or negative price rows")

df = df[~df['InvoiceNo'].astype(str).str.startswith('C')]

## After throughly checking dataset, inconsistencies were found in the description column, and
## Replacing all insonsitent values with unknown
df['Description'] = df['Description'].str.replace(r'^\?+$', 'Unknown', regex=True)

# Replace descriptions that are numbers only with Unknown
df['Description'] = df['Description'].str.replace(r'^\d+$', 'Unknown', regex=True)

df = df[~df['InvoiceNo'].astype(str).str.startswith('C')]

# See all stockcode formats
print(df['StockCode'].unique())

# Check what doesn't match the expected format
invalid_format = df[~df['StockCode'].str.match(r'^\d{5}[a-zA-Z]?$', na=False)]
print(invalid_format['StockCode'].unique())

# Replace alphabet-only stock codes with Unknown
df['StockCode'] = df['StockCode'].str.replace(r'^[a-zA-Z]+$', 'Unknown', regex=True)
print(invalid_format['StockCode'].unique())

print(df['StockCode'].value_counts().tail(10))

# Look at the actual rows before deciding
print(df.nlargest(10, 'Quantity')[['InvoiceNo', 'Description', 'Quantity', 'UnitPrice', 'Country']])

##Anomaly Remover
# Remove anything below £0
df = df[df['UnitPrice'] > 0]

print(f"Clean dataset: {df.shape[0]} rows, {df.shape[1]} columns")

# Keep original for calculations
# Create new display column with £ symbol
df['UnitPrice_formatted'] = '£' + df['UnitPrice'].round(2).astype(str)

print(df[['UnitPrice', 'UnitPrice_formatted']].head())

df.drop(columns=['UnitPrice_formatted'], inplace=True)

"""### Summary Table"""

summary = pd.DataFrame({
    'Issue Found': [
        'Missing Values',
        'Duplicates',
        'Invalid Entries',
        'Standardization'
    ],
    'Action Taken': [
        'Filled with "Unknown"',
        'Identified',
        'Corrected and Filtered',
        'Data Types and Column Names Standardized'
    ]
})

print(summary)

"""## Exploratory Data Analysis (EDA)"""

###summary statistics
df.describe () ### KPIS

# Top 5 best selling products by quantity sold
top_products = df.groupby('Description')['Quantity'].sum().sort_values(ascending=False).head(5)
print(top_products)

##Highest Revenue Generating Country
# Calculate revenue for each transaction
df['Revenue'] = df['Quantity'] * df['UnitPrice']

# Group by country and sum the revenue to find the highest revenue-generating countries
Top_Country_Revenue = df.groupby('Country')['Revenue'].sum().sort_values(ascending=False).head(5)
print(Top_Country_Revenue)

df['UnitPrice'] = df['UnitPrice'].round(1)
df['Revenue'] = df['Revenue'].round(1)
display(df[['UnitPrice', 'Revenue']].head())

## Monthly Sales Trend
# Extract month and year from Invoicedate
df['InvoiceMonth'] = df['InvoiceDate'].dt.to_period('M')

# Group by month and sum the revenue
monthly_sales_trend = df.groupby('InvoiceMonth')['Revenue'].sum().sort_values(ascending=False)
print(monthly_sales_trend)

# Most purchased product by quantity
most_purchased_product = df.groupby('Description')['Quantity'].sum().sort_values(ascending=False).head(1)
print("Most Purchased Product:\n", most_purchased_product)

# Calculate total spending per customer
customer_spending = df.groupby('CustomerID')['Revenue'].sum().sort_values(ascending=False)

# Display the top 10 customers by spending
print("Top 10 Customers by Revenue:\n", customer_spending.head(10))

"""## Visualization"""

# Create a figure and a set of subplots with a specified size
plt.figure(figsize=(10, 8))

# Generate the pie chart
# 'top_products' contains the quantities, 'top_products.index' provides labels (product descriptions)
# 'autopct' formats the percentage values displayed on each slice
# 'startangle' rotates the start of the pie chart
# 'colors' sets the color palette for the slices
plt.pie(top_products, labels=top_products.index, autopct='%1.1f%%', startangle=140, colors=sns.color_palette('coolwarm'))

# Set the title of the pie chart
plt.title('Proportion of Top 5 Selling Products by Quantity')

# Ensure the pie chart is drawn as a perfect circle
plt.axis('equal')

# Display the plot
plt.show()

# Highest Revenue Generating Countries
plt.figure(figsize=(12, 7))
sns.barplot(x=Top_Country_Revenue.values, y=Top_Country_Revenue.index, palette='viridis')
plt.title('Highest Revenue Generating Countries')
plt.xlabel('Total Revenue')
plt.ylabel('Country')
plt.show()

# Most Purchased Products
plt.figure(figsize=(12, 7))

top_products_df = top_products.reset_index()
top_products_df.columns = ['Description', 'Quantity']

sns.lineplot(x='Description', y='Quantity', data=top_products_df, marker='o')
plt.title('Top 5 Most Purchased Products by Quantity')
plt.xlabel('Product Description')
plt.ylabel('Total Quantity Sold')
plt.xticks(rotation=45, ha='right')
plt.grid(True)
plt.tight_layout()
plt.show()

plt.figure(figsize=(12, 6))
sns.lineplot(x=monthly_sales_trend.index.astype(str), y=monthly_sales_trend.values, marker='o')
plt.title('Monthly sales trend (Line Chart)')
plt.xlabel('Month')
plt.ylabel('Total Revenue')
plt.grid(True, linestyle='--', alpha=0.7)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Calculate total spending per customer
customer_spending = df.groupby('CustomerID')['Revenue'].sum().sort_values(ascending=False)

# Filter out 'Unknown' CustomerID and take the top 5 customers
top_10_customers = customer_spending[customer_spending.index != 'Unknown'].head(5).reset_index()
top_10_customers.columns = ['CustomerID', 'TotalRevenue']

plt.figure(figsize=(12, 7))
sns.barplot(x='TotalRevenue', y='CustomerID', data=top_10_customers, palette='magma', hue='CustomerID', legend=False)
plt.title('Top 5 customer purchasing behaviour')
plt.xlabel('Total Revenue')
plt.ylabel('Customer ID')
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""Insights
1. Top 5 Best-Selling Products by Quantity (Pie Chart and Line Plot)

The analysis revealed that MEDIUM CERAMIC TOP STORAGE JAR was by far the most popular product in terms of quantity sold. Its sales volume was significantly higher than every other product, suggesting that it is either a customer favourite or a frequently purchased household item.

The line plot also showed a sharp decline in sales after the top-selling product. While the remaining products were still popular among customers, their quantities sold were considerably lower. This indicates that demand is heavily concentrated around a small number of products rather than being evenly distributed across all items.

2. Highest Revenue-Generating Countries (Line Chart)

The United Kingdom generated the highest revenue by a substantial margin, contributing the majority of the company's sales income. This suggests that the retailer's customer base is primarily concentrated within the UK market.

Although countries such as the Netherlands, Germany, EIRE, and France also generated revenue, their contributions were relatively small in comparison. This highlights the importance of the UK market while also showing opportunities for further growth in international markets.

3. Monthly Sales Trends (Bar Chart)

Monthly sales figures showed a noticeable peak in December 2010, indicating a strong increase in customer spending during the holiday season. This pattern is common in the retail industry, where demand tends to rise significantly towards the end of the year.

Sales remained relatively strong during the early months of 2011, particularly in January and March. However, a gradual decline was observed in the following months, suggesting a slowdown in purchasing activity after the holiday period.

4. Customer Purchasing Behaviour (Top 5 Customers Bar Chart)

The customer analysis showed that revenue was heavily concentrated among a small group of customers. In particular, CustomerID 14646 accounted for a large share of total sales revenue, which may represent guest purchases or transactions where customer information was unavailable.

The results also demonstrate that a handful of high-value customers contribute significantly to the business's overall performance. This highlights the importance of maintaining strong relationships with loyal customers, as retaining these individuals could have a major impact on future revenue and business growth.
"""

# Save cleaned dataset
df.to_csv('OnlineRetail_Cleaned.csv', index=False)

print("Cleaned dataset exported successfully.")

from google.colab import files
files.download('OnlineRetail_Cleaned.csv')